[package]
name = "walter"
version = "0.1.0"
authors = ["Alexander McKinney <alexander.f.mckinney@durham.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
